// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection (PgBouncer) — used by the app at runtime.
    url: process.env["DATABASE_URL"],
    // Unpooled connection — Prisma Migrate needs a direct connection to
    // Neon since schema changes can't run through a connection pooler.
    directUrl: process.env["DIRECT_URL"],
  },
});
